// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quizanchos.Quiz;

#nullable disable

namespace Quizanchos.Migrations.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    partial class QuizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quizanchos.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("Quizanchos.Domain.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<int>("MinigameType")
                        .HasColumnType("int");

                    b.Property<string>("WinnerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("GameSession");
                });

            modelBuilder.Entity("Quizanchos.Domain.Entities.GameSessionPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("GameSessionId");

                    b.ToTable("GameSessionPlayer");
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.Abstractions.FeatureAbstract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<Guid>("QuizCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuizEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizCategoryId");

                    b.HasIndex("QuizEntityId");

                    b.ToTable("FeatureAbstract");

                    b.HasDiscriminator<string>("Discriminator").HasValue("FeatureAbstract");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.Abstractions.QuizCardAbstract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CardIndex")
                        .HasColumnType("int");

                    b.Property<int>("CorrectOption")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int?>("OptionPicked")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("QuizCardAbstract");

                    b.HasDiscriminator<string>("Discriminator").HasValue("QuizCardAbstract");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.QuizCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FeatureType")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionToDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuizCategories");
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.QuizEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuizEntities");
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.QuizGameSessionState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentCardIndex")
                        .HasColumnType("int");

                    b.Property<int>("GameLevel")
                        .HasColumnType("int");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsTerminatedByTime")
                        .HasColumnType("bit");

                    b.Property<int>("OptionCount")
                        .HasColumnType("int");

                    b.Property<Guid>("QuizCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SecondsPerCard")
                        .HasColumnType("int");

                    b.Property<int>("TotalCards")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId")
                        .IsUnique();

                    b.HasIndex("QuizCategoryId");

                    b.ToTable("QuizGameSessionStates");
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.QuizSessionCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CardIndex")
                        .HasColumnType("int");

                    b.Property<int>("CorrectOption")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityIdsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EntityNamesJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("OptionPicked")
                        .HasColumnType("int");

                    b.Property<string>("OptionValuesJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("QuizGameSessionStateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizGameSessionStateId", "CardIndex")
                        .IsUnique();

                    b.ToTable("QuizSessionCards");
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.QuizSessionCardAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("OptionPicked")
                        .HasColumnType("int");

                    b.Property<Guid>("QuizSessionCardId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("QuizSessionCardId", "ApplicationUserId")
                        .IsUnique();

                    b.ToTable("QuizSessionCardAnswers");
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.QuizSessionPlayerScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("QuizGameSessionStateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("QuizGameSessionStateId", "ApplicationUserId")
                        .IsUnique();

                    b.ToTable("QuizSessionPlayerScores");
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.FeatureFloat", b =>
                {
                    b.HasBaseType("Quizanchos.Quiz.Entities.Abstractions.FeatureAbstract");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("FeatureFloat");
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.FeatureInt", b =>
                {
                    b.HasBaseType("Quizanchos.Quiz.Entities.Abstractions.FeatureAbstract");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.ToTable("FeatureAbstract", t =>
                        {
                            t.Property("Value")
                                .HasColumnName("FeatureInt_Value");
                        });

                    b.HasDiscriminator().HasValue("FeatureInt");
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.QuizCardFloat", b =>
                {
                    b.HasBaseType("Quizanchos.Quiz.Entities.Abstractions.QuizCardAbstract");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("QuizCardFloat");
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.QuizCardInt", b =>
                {
                    b.HasBaseType("Quizanchos.Quiz.Entities.Abstractions.QuizCardAbstract");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("QuizCardAbstract", t =>
                        {
                            t.Property("Options")
                                .HasColumnName("QuizCardInt_Options");
                        });

                    b.HasDiscriminator().HasValue("QuizCardInt");
                });

            modelBuilder.Entity("Quizanchos.Domain.Entities.GameSession", b =>
                {
                    b.HasOne("Quizanchos.Domain.Entities.ApplicationUser", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("Quizanchos.Domain.Entities.GameSessionPlayer", b =>
                {
                    b.HasOne("Quizanchos.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizanchos.Domain.Entities.GameSession", "GameSession")
                        .WithMany("Players")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.Abstractions.FeatureAbstract", b =>
                {
                    b.HasOne("Quizanchos.Quiz.Entities.QuizCategory", "QuizCategory")
                        .WithMany()
                        .HasForeignKey("QuizCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizanchos.Quiz.Entities.QuizEntity", "QuizEntity")
                        .WithMany()
                        .HasForeignKey("QuizEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizCategory");

                    b.Navigation("QuizEntity");
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.QuizGameSessionState", b =>
                {
                    b.HasOne("Quizanchos.Domain.Entities.GameSession", "GameSession")
                        .WithMany()
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizanchos.Quiz.Entities.QuizCategory", "QuizCategory")
                        .WithMany()
                        .HasForeignKey("QuizCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("QuizCategory");
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.QuizSessionCard", b =>
                {
                    b.HasOne("Quizanchos.Quiz.Entities.QuizGameSessionState", "QuizGameSessionState")
                        .WithMany("Cards")
                        .HasForeignKey("QuizGameSessionStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizGameSessionState");
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.QuizSessionCardAnswer", b =>
                {
                    b.HasOne("Quizanchos.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizanchos.Quiz.Entities.QuizSessionCard", "QuizSessionCard")
                        .WithMany("PlayerAnswers")
                        .HasForeignKey("QuizSessionCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("QuizSessionCard");
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.QuizSessionPlayerScore", b =>
                {
                    b.HasOne("Quizanchos.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizanchos.Quiz.Entities.QuizGameSessionState", "QuizGameSessionState")
                        .WithMany("PlayerScores")
                        .HasForeignKey("QuizGameSessionStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("QuizGameSessionState");
                });

            modelBuilder.Entity("Quizanchos.Domain.Entities.GameSession", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.QuizGameSessionState", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("PlayerScores");
                });

            modelBuilder.Entity("Quizanchos.Quiz.Entities.QuizSessionCard", b =>
                {
                    b.Navigation("PlayerAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
